"""Ports the application layer depends on (ARCH-PY-USECASE: PYUC-PORTS-01/02).

`StateStore` lists exactly the persistence operations the application modules call, so
they depend on this structural Protocol instead of the concrete SQLite `Store`
(`esc_orchestrator.store`), which satisfies it without importing this module.
"""
from __future__ import annotations

from typing import Any, Protocol


class StateStore(Protocol):
    def get_run(self, run_id: str) -> dict[str, Any] | None: ...
    def get_latest_run_for_task(self, task_id: str) -> dict[str, Any] | None: ...
    def record_attempt(self, task_id: str) -> int: ...
    def get_attempt_count(self, task_id: str) -> int: ...
    def events(self, run_id: str) -> list[dict[str, Any]]: ...
    def summary(self, run_id: str) -> dict[str, Any] | None: ...
    def output_document(self, run_id: str, filename: str) -> dict[str, Any] | None: ...
    def output_yaml(self, run_id: str, filename: str) -> dict[str, Any] | None: ...
    def save_onboarding_proposal(self, repository_id: str, proposal: dict[str, Any]) -> None: ...
    def get_onboarding_proposal(self, repository_id: str) -> dict[str, Any] | None: ...
    def save_onboarding_answers(self, repository_id: str, answers: dict[str, Any], result: dict[str, Any]) -> None: ...
    def get_onboarding_answers(self, repository_id: str) -> dict[str, Any] | None: ...
    def get_pending_answers(self, repository_id: str) -> dict[str, Any] | None: ...
    def save_plan_draft(self, initiative_id: str, work_type: str, objective: str, repositories: list[str], routing: dict[str, Any], questions: list[dict[str, Any]]) -> None: ...
    def get_plan_draft(self, initiative_id: str) -> dict[str, Any] | None: ...
    def save_plan_result(self, initiative_id: str, answers: dict[str, Any], result: dict[str, Any]) -> None: ...
    def get_plan_result(self, initiative_id: str) -> dict[str, Any] | None: ...
    def get_task(self, task_id: str) -> dict[str, Any] | None: ...
    def contracts(self, task_id: str) -> dict[str, Any]: ...
